- name: create dirs
  with_items:
    - /var/lib/mariadb
  file:
    path: '{{ item }}'
    state: directory
  tags:
    - mariadb

- name: write default
  notify:
    - restart mariadb
  template:
    src: default.j2
    dest: /etc/default/mariadb
  tags:
    - mariadb

- name: prepare service
  notify:
    - restart mariadb
  template:
    src: service.j2
    dest: /etc/systemd/system/mariadb.service
  tags:
    - mariadb

- name: start service
  systemd:
    name: mariadb
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
  tags:
    - mariadb
