- name: install git
  with_items:
    - git
  package:
    name: '{{ item }}'
    state: present
  tags:
    - users

- name: create group
  with_items: '{{ users }}'
  when: item.name in users_available
  group:
    name: '{{ item.name }}'
    gid: '{{ item.uid }}'
    state: present
  tags:
    - users

- name: create user
  with_items: '{{ users }}'
  when: item.name in users_available
  user:
    name: '{{ item.name }}'
    uid: '{{ item.uid }}'
    group: '{{ item.name }}'
    shell: '{{ item.shell }}'
    groups: '{{ item.groups | join(",") }}'
    generate_ssh_key: yes
    append: yes
    createhome: yes
    state: present
  tags:
    - users

- name: install homeshick
  with_items: '{{ users }}'
  when: item.name in users_available
  become: yes
  become_user: '{{ item.name }}'
  git:
    repo: https://github.com/andsens/homeshick.git
    dest: /home/{{ item.name }}/.homesick/repos/homeshick
  tags:
    - users

- name: clone castles
  with_subelements: ['{{ users }}', castles]
  when: item.0.name in users_available
  become: yes
  become_user: '{{ item.0.name }}'
  git:
    repo: https://github.com/{{ item.1 }}.git
    dest: /home/{{ item.0.name }}/.homesick/repos/{{ item.1 | basename }}
  tags:
    - users

- name: link castles
  with_subelements: ['{{ users }}', castles]
  when: item.0.name in users_available
  become: yes
  become_user: '{{ item.0.name }}'
  command: /home/{{ item.0.name }}/.homesick/repos/homeshick/bin/homeshick -f -b -q link {{ item.1 | basename }}
  tags:
    - users

- name: write sshkeys
  with_items: '{{ users }}'
  when: item.name in users_available
  authorized_key:
    user: '{{ item.name }}'
    key: '{{ item.sshkeys }}'
    exclusive: yes
    state: present
  tags:
    - users
