---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: terraform-check
  image: jmccann/drone-terraform:5
  pull: always
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    TF_VAR_hcloud_token:
      from_secret: hcloud_token
    TF_VAR_cloudflare_token:
      from_secret: cloudflare_token
    TF_VAR_github_token:
      from_secret: github_token
  settings:
    tf_version: 0.12.1
    root_dir: terraform/
    actions:
      - validate
      - plan
  when:
    event:
    - pull_request

- name: terraform-apply
  image: jmccann/drone-terraform:5
  pull: always
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
    TF_VAR_hcloud_token:
      from_secret: hcloud_token
    TF_VAR_cloudflare_token:
      from_secret: cloudflare_token
    TF_VAR_github_token:
      from_secret: github_token
  settings:
    tf_version: 0.12.1
    root_dir: terraform/
    actions:
      - validate
      - plan
      - apply
  when:
    event:
      exclude:
      - pull_request

- name: ansible-check
  image: plugins/ansible:1
  pull: always
  environment:
    HCLOUD_TOKEN:
      from_secret: hcloud_token
  settings:
    syntax_check: true
    playbook: ansible/playbook.yml
    galaxy: ansible/requirements.yml
    inventory: ansible/inventory
  when:
    event:
    - pull_request

- name: ansible-apply
  image: plugins/ansible:1
  pull: always
  environment:
    HCLOUD_TOKEN:
      from_secret: hcloud_token
  settings:
    private_key:
      from_secret: ansible_sshkey
    vault_password:
      from_secret: ansible_vault
    playbook: ansible/playbook.yml
    galaxy: ansible/requirements.yml
    inventory: ansible/inventory
  when:
    event:
      exclude:
      - pull_request

- name: notify
  image: plugins/matrix:1
  pull: always
  settings:
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
  when:
    event:
    - push
    - tag
    status:
    - failure

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**
