workspace:
  base: /srv/app
  path: src/github.com/umschlag/umschlag-infra

branches:
  - master

pipeline:
  terraform-check:
    image: jmccann/drone-terraform:5
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key, tf_var_cloudflare_token, tf_var_github_token ]
    root_dir: terraform/
    actions:
      - validate
      - plan
    when:
      event: [ pull_request ]

  terraform-apply:
    image: jmccann/drone-terraform:5
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key, tf_var_cloudflare_token, tf_var_github_token ]
    root_dir: terraform/
    actions:
      - validate
      - plan
      - apply
    when:
      event: [ push, tag ]

  notify-matrix:
    image: plugins/matrix:1
    pull: true
    secrets: [ matrix_roomid, matrix_username, matrix_password ]
    when:
      local: false
      event: [ push ]
      status: [ changed, failure ]
