- name: install packages
  with_items:
    - lsb-release
    - figlet
    - update-motd
  package:
    name: '{{ item }}'
    state: present
  tags:
     - motd

- name: disable files
  with_items: '{{ motd_disable }}'
  file:
    path: /etc/update-motd.d/{{ item }}
    state: absent
  tags:
     - motd

- name: write files
  with_items: '{{ motd_files }}'
  template:
    src: '{{ item.template }}'
    dest: /etc/update-motd.d/{{ item.dest }}
    mode: u=rwx,g=rx,o=rx
  tags:
     - motd
