- name: write default
  notify:
    - restart downloads
  template:
    src: default.j2
    dest: /etc/default/downloads
  tags:
    - downloads

- name: prepare service
  notify:
    - restart downloads
  template:
    src: service.j2
    dest: /etc/systemd/system/downloads.service
  tags:
    - downloads

- name: start service
  systemd:
    name: downloads
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
  tags:
    - downloads
