- name: write default
  notify:
    - restart github-exporter
  template:
    src: default.j2
    dest: /etc/default/github-exporter
  tags:
    - github-exporter

- name: prepare service
  notify:
    - restart github-exporter
  template:
    src: service.j2
    dest: /etc/systemd/system/github-exporter.service
  tags:
    - github-exporter

- name: start service
  systemd:
    name: github-exporter
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
  tags:
    - github-exporter
