firewall_additions: []
firewall_defaults:
  - rule: allow
    port: 22022
    proto: tcp
  - rule: allow
    port: 80
    proto: tcp
  - rule: allow
    port: 443
    proto: tcp
  - rule: allow
    port: 8000
    proto: tcp

firewall_private_ips: []
firewall_public_ips: []
