- src: https://github.com/rolehippie/apt
  version: master

- src: https://github.com/rolehippie/base
  version: master

- src: https://github.com/rolehippie/cronlist
  version: master

- src: https://github.com/rolehippie/docker
  version: master

- src: https://github.com/rolehippie/firewall
  version: master

- src: https://github.com/rolehippie/gai
  version: master

- src: https://github.com/rolehippie/hetzner
  version: master

- src: https://github.com/rolehippie/hosts
  version: master

- src: https://github.com/rolehippie/ipv6nat
  version: master

- src: https://github.com/rolehippie/mlocate
  version: master

- src: https://github.com/rolehippie/motd
  version: master

- src: https://github.com/rolehippie/nullmailer
  version: master

- src: https://github.com/rolehippie/resolved
  version: master

- src: https://github.com/rolehippie/root
  version: master

- src: https://github.com/rolehippie/sudo
  version: master

- src: https://github.com/rolehippie/swap
  version: master

- src: https://github.com/rolehippie/sysctl
  version: master

- src: https://github.com/rolehippie/telegraf
  version: master

- src: https://github.com/rolehippie/traefik
  version: master

- src: https://github.com/rolehippie/users
  version: master
