- name: write default
  notify:
    - restart dockerhub-exporter
  template:
    src: default.j2
    dest: /etc/default/dockerhub-exporter
  tags:
    - dockerhub-exporter

- name: prepare service
  notify:
    - restart dockerhub-exporter
  template:
    src: service.j2
    dest: /etc/systemd/system/dockerhub-exporter.service
  tags:
    - dockerhub-exporter

- name: start service
  systemd:
    name: dockerhub-exporter
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
  tags:
    - dockerhub-exporter
